all_handles = [
"nongi",
"UWPLP",
"kcherdakov",
"Qalmee",
"genybr",
"Mazx1998",
"stMark",
"Thundbird",
"bedsus",
"Allen_Mett",
"Shadow-of-Dreams",
"Levcor",
"andrew_raiden",
"niloniol",
"Mary12",
"Minddarkness",
"PowerOfBalls",
"Alecks",
"Tornem",
"ikrisi",
"RushBush",
"fkz_12",
"Arishenk",
"Flanterz",
"Fonriter98",
"ruban",
"jeanstefanovich",
"Brandon_Roadgears_",
"Soul_Catcher",
"shise",
"Izeytee",
"wartemw",
"deluck",
"gedenteen",
"Marks53",
"Dream_Tea",
"Kagary",
"F14rk",
"JustBoss",
"Animeshka",
"Lampcomm",
"Nottey",
"alexger1999",
"Tod-cun",
"osipovcf",
"MikeAirone",
"Karina8941",
"Aleksey-Kn",
"Makisto",
"Asakujaku",
"Hostel_B",
"fredboy",
"aldinger_a",
"Restov",
"BarebuhPuh",
"virride",
"Hazzi",
"fancyFox",
"Sheshesi",
"Gadyka",
"Grawyn",
"Baburr",
"tryblyat7",
"MangriMen",
"_HiFive",
"QWOP1234",
"Daniil_hrpo",
"isugihere",
"sweetechka",
"El_Duderino",
"QualDiv2",]

# ID Google Sheets документа (можно взять из его URL)
spreadsheet_id = '1gJYZf7wQE0ReIgR8idpZnqqgSPKQmlkQtnaO3XwGcJI'

token = "0d58da257245ff2850c27b089689277341398df66c38a7ff052417f0f89ccef5c6e902a30e934c67f6bc0"

bad_words = ['твердохлеб', 'петуч', 'лох']